@hostclientes = http://localhost:3000
@hostpedidos = http://localhost:3001
@hostpagamentos = http://localhost:3002

@idcliente = a6c674de-42a9-4792-978d-9cb94c0ddfc2

### MS - Clientes ###

GET {{hostclientes}}/clientes

###

GET {{hostclientes}}/clientes/{{idcliente}}

###

POST {{hostclientes}}/clientes HTTP/1.1
content-type: application/json

{
 "nome": "Zé Cláudio",
 "email": "zeclaudio@email.com",
 "telefone": "8181818181",
 "endereco": "Rua tal, beco da tilapia nº 39. Terra do nunca - Lua",
 "enderecoCobranca": "Lado oculto da lua Nº 101. Lua - Espaço",
 "documentoIdentificacao": "12392301293",
 "preferencias": "video game, pizza, praia"
}

###

PUT {{hostclientes}}/clientes/{{idcliente}} HTTP/1.1
content-type: application/json

{
 "nome": "Zé Cláudio 222",
 "email": "zeclaudio@email.com",
 "telefone": "8181818181",
 "endereco": "Rua tal, beco da tilapia nº 39. Terra do nunca - Lua",
 "enderecoCobranca": "Lado oculto oposto da lua Nº 101. Lua - Espaço",
 "documentoIdentificacao": "43243212343",
 "preferencias": "video game, pizza, praia"
}

###

### MS - Pedidos ###

GET {{hostpedidos}}/clientes

###

GET {{hostpedidos}}/pedidos

###

POST {{hostpedidos}}/pedidos HTTP/1.1
content-type: application/json

{
 "idCliente": "{{idcliente}}",
 "items": ["God of war - PS5", "Evil West"],
 "dadosCartao": "1000000"
}


### MS - Pagamentos ###

GET {{hostpagamentos}}/clientes

###

GET {{hostpagamentos}}/pagamentos